apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sata # adjust storage if needed
  resources:
    requests:
      storage: 5Gi
