---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgC2RwptV7t/FbyY6F5gR8laTP13Bw7n3HbagyBrDwsq0mUlkGIT7eg8wHLMkr8TvIWhOY/GclzoD9YrisFt/impoyo8xtyulAMzHTvI6jmZ5kD3s9x2tthc4wpS/P+A09c+4x6vFBSxZv7NGgaU2eRDJZKjKMsxwC1Iuw2+ERFCe02+TWX6BrlhW6Gse3WYdcBQr5IplwPK8gGmbCDHtz4bsH1MWrWVHMA/+5zDTswDplF92gLoq5DplgS6fh7PliNWZN0kM2XSnZKDXxeqwUdaWOg6rNAreBMy73VoDq7BE7iF6+ml+0guYfUqKXkJvEnRj+eBkbGKVb3I7ic+jBqOfW9bTpNP0VAyc0sg4pIVoLIZ/VjijitnjkO7oa5SStnWDgH1wnCBjrWgPl9Kv+v7X6YuN8y0ZH+p7YU+k7AjG4Yc4pKZhGxYxciryUPGoElxaRwdW2BCNbiOeQItzl6k9fH38uAao8dNDafG4HXXrisHCh/TxHkpYqxPAq+amWHQ2N15cgm6KMn+MhMjD8lE8/vy1J9E/wqLrWxjlxNx6m/MBth494bviQcwvvS2+vv419cjz41phskyfxmdAoPy1cZdJ+LPpB4j0bOfQGKpoGy95lwAA4uUoxNWUl2/ELF5dtCO0YwAemwjYI5fj3rjPJJJbQ11wOJZbiDV/GiRn/Vqebn7R61uFFC2sYadk5wmpzWmz2VFKKpnQLVxUDvjs3UXSDQ8VgfsEVGyK0yWBatsfGfblR6X
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cert-manager
