apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: quickwit
  namespace: flux-system
spec:
  chart:
    spec:
      chart: quickwit
      sourceRef:
        kind: HelmRepository
        name: quickwit
      version: "0.7.1"
  interval: 1h0m0s
  timeout: 20m
  releaseName: quickwit
  targetNamespace: quickwit
  values:
    environmentFrom:
    - secretRef:
        name: quickwit-env
    indexer:
      replicaCount: 2
    metastore:
      replicaCount: 2
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
    config:
      default_index_root_uri: s3://quickwit/quickwit-indexes
      storage:
        s3:
          endpoint: https://62f4eb07502220f46e423c5a98396b16.r2.cloudflarestorage.com
          access_key_id: ${accessKeyId}
          secret_access_key: ${secretAccessKey}
          region: auto