apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: clickhouse
    namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  interval: 1h0m0s
  timeout: 10m
  releaseName: clickhouse
  targetNamespace: clickhouse
  values:
    resourcesPreset: xlarge
    auth:
      existingSecret: clickhouse-password
      existingSecretKey: admin-password
    keeper:
      enabled: true
    persistence:
      enabled: true
      size: 20Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    zookeeper:
      enabled: false
    logLevel: warning