---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clickhouse-password
  namespace: clickhouse
spec:
  encryptedData:
    admin-password: AgBz5Y1okOk1aLSootNb5M58nwMFMENhgd1D2+8V/N2iTo6WVjamns0u9L5+PjF33QNLXEuF2bYLk30o51RzSLzClYweYpFayh1gmYZ+kX9YOduFsV8Um+FQ/k5I9fqHFftkGtCQLBxd7TFjIKv+DimEsGkOeSO5VracalNT5G+6mlaxfKWrp6ceWtKxyE9pnQnnIivRaZIjEyyRggUk/Cra1LBdiuF2GzHRAYP2ovGUyRsQmmIkM85vDzTXCWRM48XxcWl7UhZv37RAnzfYpIGl2+D9S9CinP9mo8Igalip3uzm6ynMoZsE0hqrb1ZrlpZVWtMYMmdatbHvi/ogrXSfU7Hm7Iokehizx0845Cg4Ar4hen8MNxB9hQKKHmZ11BNkNQyvf3vB/t2sm3JaI+VktOB8c0NOl2T7WpbEQxvQU8HZIp/Qlz+p1Es7MVszFtOYGYD/1wph1wnDtrvL2kyNPpPgW/zxUthOZwJ0TS7P7sCL8cMmYLSZabMC1FTabtUdH8F6dqasObx+oO5vyo5HlcrA/xlbjRNFmrO+4dCtJF71gQrftjSsMz6dbe03CxKgo8smJozdZxDmg4+umdjjhm/bi69MWTLyPh9xKPt7R5fzBXtwq2eKEdM5CROk0a+C5V6mKFJ3EwqEfsJcpwrI6rBthy7+ZMKYZvCEXxVWvCbn8V8dq9ERy+/87fKhN0WQJW56lZbtiLzITEm4deJYCYYHvmQti9v9rlkHmDry1WX8cs55XjFamVOYNYhCvw+FZfEUNtxQsKyJXLE=
  template:
    metadata:
      creationTimestamp: null
      name: clickhouse-password
      namespace: clickhouse
