apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: yugabytedb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: yugabyte
      sourceRef:
        kind: HelmRepository
        name: yugabytedb
      version: "2024.1.2"
  interval: 1h0m0s
  timeout: 20m
  releaseName: yugabyte
  targetNamespace: yugabyte
  values:
    enableLoadBalancer: false