apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: "1.17.1"
  interval: 1h0m0s
  timeout: 10m
  releaseName: cilium
  targetNamespace: kube-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values