---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
      version: 1.72.0
  install:
    crds: Create
  interval: 1h0m0s
  targetNamespace: tailscale
  upgrade:
    crds: CreateReplace
