---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
  ref:
    tag: v0.4.1
    verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "https://token.actions.githubusercontent.com"
        subject: "^https://github.com/gimlet-io/capacitor.*$"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: "./"
  sourceRef:
    kind: OCIRepository
    name: capacitor
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor-ingress
  namespace: flux-system
spec:
  targetNamespace: flux-system
  dependsOn:
    - name: tailscale-operator
    - name: capacitor
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: ./apps/capacitor/ingress
  sourceRef:
    kind: GitRepository
    name: flux-system