apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: trivy-operator
    namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  interval: 1h0m0s
  timeout: 10m
  releaseName: trivy-operator
  targetNamespace: trivy-operator
  values:
    serviceMonitor:
      enabled: true
