---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-operator
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./apps/cloudnative-pg/operator
  dependsOn:
    - name: kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 15m0s
  wait: true
