---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backup-creds
  namespace: postgres
spec:
  encryptedData:
    accessKeyId: AgCkGSAmM2nTU/w89brsp8cY0nKTfeOelcMLhjqgbr3msX/zwbjQwznNSszmCu8Q75usT7/eCcrJ5FVxyfffMk60ljJp0YFn6HhgErHmhB8HxtcEo3djvQK5f2Hx5Wboe8IXR8aZqIi9m1XmkrbtCbpDJl4ykIA9Z5CzfSJj3Hsy+Hv9tXAqIUcchX3fGyskFGpmTyrvO2fO4JDB+A35TOVtxjMUj1O6Z2jCYEAt23VaP7S2SLK2aaw8jywMHVX/vExt1y+kpAQQpqoGFvn4SVAhbhWYzjmpJw80nq07nSOlYK/t6wq3OyJDcCE9B1qNvuPyxWNdpwmUEx7GegqgfW/qXL+2HVvoR0NFK8lOQZdzR7ngg6dLAVBOUMzQwpTyC5A/TUdMkisuog3hJ77cDVt/9t9d5JFbXVEtK14RVagBH4QgZjL7SAKZox3ZWXCxMS9MqPK1NKu3EOmfxG78NrQYHQQ1+sUuLJXnUoxFqKdBXTdPxJ/IVkPDG2gvMWC/87L3uoaZDw+PhLgx0S2VCUlsZ2lYB+0dHVDYMFXGkCvGKziI09X21D6eWA7+B2sn5F0FVJIlaw8n5bqbNKB/bVKTR+LyY86s/JQHkR6DdvwsJritr7T5ahrFkIz3e7N+bnqZD43U8mRis0GRKoCXLFJq/Mlj5oN76GhF7tSbYzJTAo7D451zUr3cIcVIcyH25XQuZprDD8a6EXd81zmFDP/97J34co4rEuQ=
    secretAccessKey: AgCqH6GM8VmcbWACtelQiGqLMhFcRezpaJmmQatvm+iKq0gOdMzheIf/mzYg+sWD0qt2Gz4U5yXnhmNzVb9L8d/+xdIJRK4kP+SjyfAUkDiedTLwRQelMJ3fSCWpkV7CKRzzX+FzBdFZNQQd98uomaCDpYI9frx62JTl2EukasiDRP0/snhiL597YIbmEcdbGkdO3N8zJ+EljNBhKj+LHY5t/Kw1FS69oxcnPeD70JdM3OmGJrZaP1nGkkTZfcHS+xOvztgCqXcSrM9hJVgFIRfFiTjI58cEwVzvmbM0e6qyjtAPisdR1YyhQuVLfnZ7czL4U/P8fkHR2VtX7waVKrCVav/amzb11F8/QaVwd1kMS7HF5hg8XgSEcSLnYLK8iCxU0qnXuOu6nFohH0rF+XkQIEHDv9ZhS5ohgNNq8bFpoCBAgTjnZkn1XYq2j3qsZfmi5n5u3Gm4JLR+gQSXb/Id2X3x7l7w61asIOYic1lK2eFMdmrv1sKpunu3pNKhEAqG6yU4ulPo2A+LABUOoFwhzd1jcIhqCPpSVQbIv0w3dILCIsVVXdCvoNk7OchUMkliC5ujL1Awm/GJltndwCKztmsuJhOh3+AUSe0w2cXvIhv1rvLAhWJdhk3loShiGcRNhllkAOkJrRJRZJawIRNdM9iF32Ftn3OZQeiotfr+/JLTzsBqD2kOFACWLiO+c77J/mSuEvyjNk9fsZDBWovbgkRc/9sq3fjvrxXfd2rtSXEsE4e6UITHMihfts37oKc=
  template:
    metadata:
      creationTimestamp: null
      name: backup-creds
      namespace: postgres
    type: Opaque
