apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-db
  namespace: postgres
spec:
  instances: 3
  storage:
    storageClass: sata
    size: 5Gi
  monitoring:
    enablePodMonitor: true
  managed:
    roles:
    - name: app
      createdb: true
      login: true
    - name: quickwit
      createdb: true
      login: true
      ensure: present
      passwordSecret:
        name: quickwit-user-password
  backup:
    retentionPolicy: '30d'
    barmanObjectStore:
      endpointURL: https://62f4eb07502220f46e423c5a98396b16.r2.cloudflarestorage.com
      destinationPath: s3://postgres-backup/
      s3Credentials:
        accessKeyId:
          name: backup-creds
          key: accessKeyId
        secretAccessKey:
          name: backup-creds
          key: secretAccessKey
      wal:
        compression: gzip
        maxParallel: 8
      data:
        compression: gzip