apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-db-pooler
  namespace: postgres
spec:
  cluster:
    name: postgres-db

  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"