---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quickwit-user-password
  namespace: postgres
spec:
  encryptedData:
    password: AgDEkvQysVBn6J5VcpJ2DAI6neUskZJQbHdZrNTzvmLfDOkJc1SafvH/kU5n40SaMD6WL6fOe5uxr3snkHbHGYdZJkvvKxozhxPuYagy5s2jSnao5AQ4qVVCcWTgWoYdYE2WZ4AUJ5e8A3FtQr2OHGQtA6O7MBT4B9Hf9XH9EussQPubfSUe1lK+QF/d6swGqUshT5J2ajpmiwfNUQqMPeluzqDHv7gZM5wNPw3nGOwRkGZMW7vf3RhdwSoNJR6ELXt/VYw8onX3gVRxoPWAGI5QNoLcLo+k4pq6qMMUMG7w7jfx1EK8QIqePsRS+72COf/M1Qx6nJFK1CsyHnJlQUWN99SCVKoBEvtVNEdHLP6urL9Wod5yvB7Cc1Mg1GltZ51Ku2KeSVRFZiaPa+Cl1usKTdY/BHxIrIh6V6Kc+undwNvWxmdC2ohdsLN8nBE8MrVHNq3wB+2DjjD0rufQQoBdn8B9F06qgAbi+ka3kXXp+Ur2+d6Ix0KlganIzrb66Gn9HlTzNu9tO24M9WUjCNFTOJiP6fYLc9M4gxT92mgyl6pYixu2pro6+3nKk31ct8oaPk01oUxCkyRMrNFc3CBOqnEC7BYKtATj4TaO+gI0BJyJp0+sPk7ZteOQA8v3tCy/Xq83vsSxaELouXCEj4fDKRx7U7Q+xyTOFogVDSCoAYedL8PIaJR6HcPcJBXRnep75Y99N8gFXmaF5FiF5dETn4HnaSg1dic2LVY+l1qEyCOo141YYIrVWtEkgZ4slgjQbb1iOGZtKiyHSoeYJQ/Q
    username: AgAFagvlnTPMh0VJC2SHppB/2Ybo7n1O7vjxi2yqSP49wltsNLrAP/Ple9VmFkAKNs6JtNogws50OgM4/MkjUbWu0/Oic+Tp/5aMFVbBCMohwoPpBJuUw/kTlDYRB5Pf9wpIIkWgO5kq39xF6ddoOOz3hzTCG17PdGoQA9/mAa2skRYSXMo8gsX/e3b7nKpJS+fXPWqaD6JynSzpFgie3rUeUPIlEPDk6JPpiyNWvEEEkiEWNAztxho0JxVj/zWXZMY2Vj5ZXma0MNJ2Kh2U02o9OuOQzTE9WPUBBsw2kPJ0Mb7dGlGGtWC395TB9qA5CtHci0DGspOdd11s1G/K2DWihq2rCkmP33bZTnnZaO9d9hbkE6RaErNykrfzE36yYsMUI3xomAqtTSB10j40yaul293EjEURbWteFx6vpTowzbxMuiIikfgWqpBAe7v0GEigPkSn87pnH3nLE4CseA9UX+SUjYezvo23suuWHNA3jE7QugP2O6IYnK/9zzqtI1oLnctLxQ7hXGgbaxN7bW9l9qjw5c/jUBgLcTBqFEuACwxaSPRxMwx4ikuq3T791MwqMkgYgiZpyEuQnt85jSgKE5GvdVCUyY8CAknoYBp4JpxJn38vkS0Mr8EeUHFKVOXEyQ00I3oaNuMeg+KXyAT7NIJpDuMOPtTp+gUrgJRxHLLReVwIi3ucsvh7NnS9WP2Ceh6Nublk8g==
  template:
    metadata:
      creationTimestamp: null
      labels:
        cnpg.io/reload: "true"
      name: quickwit-user-password
      namespace: postgres
    type: kubernetes.io/basic-auth
