apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
      version: "0.21.6"
  interval: 1h0m0s
  timeout: 15m
  releaseName: cnpg
  targetNamespace: cnpg-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 2
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true