apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parseable-ingress
  namespace: parseable
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: parseable-querier-service
      port:
        number: 80
  tls:
    - hosts:
      - parseable