apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: parseable
  namespace: flux-system
spec:
  chart:
    spec:
      chart: parseable
      sourceRef:
        kind: HelmRepository
        name: parseable
      version: "2.4.0"
  interval: 1h0m0s
  timeout: 10m
  releaseName: parseable
  targetNamespace: parseable
  values:
    parseable:
      store: s3-store
      highAvailability:
        enabled: true
      persistence:
        staging:
          enabled: false
        ingestor:
          enabled: true
          size: 5Gi
          storageClass: null
        data:
          enabled: false
        ## enabling the disk on querier adds the hot-tier.
        querier:
          enabled: false
          storageClass: null
          size: 20Gi
      gcsModeSecret:
        enabled: false
      s3ModeSecret:
        enabled: true
      metrics:
        serviceMonitor:
          enabled: false
