apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: "60.2.0"
  interval: 1h0m0s
  timeout: 10m
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      defaultDashboardsEditable: false
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
