apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: flux-system
spec:
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
      version: "4.3.1"
  interval: 1h0m0s
  releaseName: falco
  targetNamespace: falco
  values:
    tty: true
    driver:
      kind: ebpf
    falcosidekick:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRules:
        enabled: true
      config:
        webhook:
          address: http://ntfy-svc.ntfy/falco
          minimumpriority: alert
      webui:
        enabled: false