apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: flux-system
spec:
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
      version: "4.5.1"
  interval: 1h0m0s
  timeout: 10m
  releaseName: falco
  targetNamespace: falco
  values:
    tty: true
    driver:
      kind: ebpf
    customRules:
      # Containers we run that contact k8s API server
      rules-k8s-containers-macro.yaml: |-
        - macro: k8s_containers
          override:
            condition: append
          condition: or (container.image.repository in (
            registry.k8s.io/kube-state-metrics/kube-state-metrics,
            docker.io/bitnami/sealed-secrets-controller,
            docker.io/kubernetesui/dashboard,
            docker.io/tailscale/k8s-operator,
            docker.io/tailscale/tailscale,
            quay.io/kiwigrid/k8s-sidecar,
            quay.io/platform9/dashboard-metrics-scraper,
            quay.io/prometheus/prometheus,
            ghcr.io/aquasecurity/trivy-operator,
            ghcr.io/cloudnative-pg/cloudnative-pg,
            ghcr.io/cloudnative-pg/postgresql,
            ghcr.io/gimlet-io/capacitor,
            ghcr.io/fluxcd/helm-controller,
            ghcr.io/fluxcd/kustomize-controller,
            ghcr.io/fluxcd/source-controller,
            ghcr.io/fluxcd/notification-controller))
    falcosidekick:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRules:
        enabled: true
      config:
        webhook:
          address: http://ntfy-svc.ntfy/falco
          minimumpriority: notice
      webui:
        enabled: true
        redis:
          storageEnabled: false